### PR TITLE
issue updating iobackend/api_backend.yaml and iobackend/api_notification.yaml

### PR DESCRIPTION
**Pull request by gquadrati**
**What was my goal?**

To test model generation against updated io_backend openapi ([api_backend.yaml](https://raw.githubusercontent.com/pagopa/io-backend/master/api_backend.yaml) and [api_notification.yaml](https://raw.githubusercontent.com/pagopa/io-backend/master/api_notification.yaml)

To test it, I copied those two files under openapi/_test/ folder of this repo and updated their ref of io-functions-commons to version 18.0.7

**The issue**

While generating the models I got this error:

image

@balanza @gunzip have I done something wrong in this process? Can you try yourself (It should be just a matter of checkout the folder and do a `yarn build`)?
Notice that this problem is related to one of the two spec model that I've update (`CreatedMessageWithContent`)

### CODE REVIEW

**Comment by gunzip** [comment]
This is a know gotcha that should be documented someway. The reason is that you have to reference all custom schema even when they are transitive dependencies. In this case you must add 

```
ServiceId:
    $ref: "https://raw.githubusercontent.com/pagopa/io-functions-commons/v18.0.7/openapi/definitions.yaml#/ServiceId"

```

to the specs

**Comment by balanza** [comment]
It's explained here: https://github.com/pagopa/io-utils#a-model-file-for-a-definition-is-not-generated, but I see it's not immediate to reach out

**Comment by gquadrati** [comment]
Ok, understood.. thanks!

**Pull request closed without merging**
